"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { isAdmin } from "@/lib/session";

const categorySchema = z.object({
  slug: z.string().min(1, "slug חובה").regex(/^[a-z0-9-]+$/, "slug: אותיות קטנות באנגלית"),
  name: z.string().min(1, "שם חובה"),
  nameEn: z.string().min(1, "שם באנגלית חובה"),
  cta: z.string().default(""),
  image: z.string().nullable().optional(),
  description: z.string().default(""),
  seoTitle: z.string().default(""),
  seoDescription: z.string().default(""),
  sortOrder: z.coerce.number().int().default(0),
  isActive: z.coerce.boolean().default(true),
});

export type CategoryFormState = {
  ok: boolean;
  error?: string;
  fieldErrors?: Partial<Record<keyof z.infer<typeof categorySchema>, string>>;
};

function formDataToObject(formData: FormData) {
  const obj: Record<string, FormDataEntryValue | boolean | null> = {};
  for (const [k, v] of formData.entries()) obj[k] = v;
  obj.isActive = formData.get("isActive") === "on" || formData.get("isActive") === "true";
  if (obj.image === "") obj.image = null;
  return obj;
}

async function assertAdmin() {
  if (!(await isAdmin())) throw new Error("Unauthorized");
}

export async function createCategory(_: CategoryFormState, formData: FormData): Promise<CategoryFormState> {
  await assertAdmin();
  const parsed = categorySchema.safeParse(formDataToObject(formData));
  if (!parsed.success) {
    const fe: CategoryFormState["fieldErrors"] = {};
    for (const issue of parsed.error.issues) {
      const k = issue.path[0] as keyof z.infer<typeof categorySchema>;
      if (!fe[k]) fe[k] = issue.message;
    }
    return { ok: false, error: "ולידציה נכשלה", fieldErrors: fe };
  }
  try {
    await prisma.category.create({
      data: {
        // id auto-generated by Prisma (cuid)
        slug: parsed.data.slug,
        name: parsed.data.name,
        nameEn: parsed.data.nameEn,
        cta: parsed.data.cta,
        image: parsed.data.image ?? null,
        description: parsed.data.description,
        seoTitle: parsed.data.seoTitle,
        seoDescription: parsed.data.seoDescription,
        sortOrder: parsed.data.sortOrder,
        isActive: parsed.data.isActive,
      },
    });
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : "שגיאה ביצירה" };
  }
  revalidatePath("/admin/categories");
  redirect("/admin/categories");
}

export async function updateCategory(
  categoryId: string,
  _: CategoryFormState,
  formData: FormData
): Promise<CategoryFormState> {
  await assertAdmin();
  const parsed = categorySchema.safeParse(formDataToObject(formData));
  if (!parsed.success) {
    const fe: CategoryFormState["fieldErrors"] = {};
    for (const issue of parsed.error.issues) {
      const k = issue.path[0] as keyof z.infer<typeof categorySchema>;
      if (!fe[k]) fe[k] = issue.message;
    }
    return { ok: false, error: "ולידציה נכשלה", fieldErrors: fe };
  }
  try {
    await prisma.category.update({
      where: { id: categoryId },
      data: {
        slug: parsed.data.slug,
        name: parsed.data.name,
        nameEn: parsed.data.nameEn,
        cta: parsed.data.cta,
        image: parsed.data.image ?? null,
        description: parsed.data.description,
        seoTitle: parsed.data.seoTitle,
        seoDescription: parsed.data.seoDescription,
        sortOrder: parsed.data.sortOrder,
        isActive: parsed.data.isActive,
      },
    });
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : "שגיאה בעדכון" };
  }
  revalidatePath("/admin/categories");
  revalidatePath(`/category/${parsed.data.slug}`);
  redirect("/admin/categories");
}

export async function deleteCategory(categoryId: string) {
  await assertAdmin();
  try {
    const productCount = await prisma.product.count({ where: { categoryId } });
    if (productCount > 0) {
      return {
        ok: false,
        error: `יש ${productCount} מוצרים בקטגוריה. העבירו או מחקו אותם קודם.`,
      };
    }
    await prisma.category.delete({ where: { id: categoryId } });
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : "שגיאה במחיקה" };
  }
  revalidatePath("/admin/categories");
  return { ok: true };
}
