"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { isAdmin } from "@/lib/session";

const productSchema = z.object({
  slug: z.string().min(1, "slug חובה").regex(/^[a-z0-9-]+$/, "slug: אותיות קטנות באנגלית, מספרים, מקפים"),
  categoryId: z.string().min(1, "בחרו קטגוריה"),
  name: z.string().min(1, "שם חובה"),
  nameEn: z.string().default(""),
  meta: z.string().default(""),
  description: z.string().default(""),
  price: z.coerce.number().int().min(0, "מחיר לא תקין"),
  originalPrice: z.coerce.number().int().min(0).nullable().optional(),
  badge: z.string().nullable().optional(),
  badgeType: z.string().nullable().optional(),
  sku: z.string().min(1, "מק״ט חובה"),
  stock: z.coerce.number().int().min(0).default(0),
  image: z.string().min(1, "תמונה ראשית חובה"),
  imagesText: z.string().default(""), // newline-separated paths
  specsText: z.string().default(""), // "key: value" per line
  sizesText: z.string().default(""), // comma-separated
  careInstructions: z.string().nullable().optional(),
  sortOrder: z.coerce.number().int().default(0),
  isActive: z.coerce.boolean().default(true),
  isFeatured: z.coerce.boolean().default(false),
});

export type ProductFormState = {
  ok: boolean;
  error?: string;
  fieldErrors?: Partial<Record<keyof z.infer<typeof productSchema>, string>>;
};

function parseTextLists(input: z.infer<typeof productSchema>) {
  const images = input.imagesText
    .split(/\r?\n/)
    .map((s) => s.trim())
    .filter(Boolean);
  if (images.length === 0) images.push(input.image);

  const specs: Record<string, string> = {};
  for (const line of input.specsText.split(/\r?\n/)) {
    const [key, ...rest] = line.split(":");
    if (!key || rest.length === 0) continue;
    const k = key.trim();
    const v = rest.join(":").trim();
    if (k && v) specs[k] = v;
  }

  const sizes = input.sizesText
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);

  return { images, specs, sizes };
}

function formDataToObject(formData: FormData) {
  const obj: Record<string, FormDataEntryValue | boolean> = {};
  for (const [k, v] of formData.entries()) obj[k] = v;
  // Convert checkbox values
  obj.isActive = formData.get("isActive") === "on" || formData.get("isActive") === "true";
  obj.isFeatured = formData.get("isFeatured") === "on" || formData.get("isFeatured") === "true";
  // Empty originalPrice → null
  if (obj.originalPrice === "") obj.originalPrice = null as unknown as FormDataEntryValue;
  if (obj.badge === "") obj.badge = null as unknown as FormDataEntryValue;
  if (obj.badgeType === "") obj.badgeType = null as unknown as FormDataEntryValue;
  if (obj.careInstructions === "") obj.careInstructions = null as unknown as FormDataEntryValue;
  return obj;
}

async function assertAdmin() {
  if (!(await isAdmin())) {
    throw new Error("Unauthorized");
  }
}

export async function createProduct(_: ProductFormState, formData: FormData): Promise<ProductFormState> {
  await assertAdmin();
  const parsed = productSchema.safeParse(formDataToObject(formData));
  if (!parsed.success) {
    const fe: ProductFormState["fieldErrors"] = {};
    for (const issue of parsed.error.issues) {
      const k = issue.path[0] as keyof z.infer<typeof productSchema>;
      if (!fe[k]) fe[k] = issue.message;
    }
    return { ok: false, error: "ולידציה נכשלה", fieldErrors: fe };
  }
  const { images, specs, sizes } = parseTextLists(parsed.data);
  try {
    await prisma.product.create({
      data: {
        // id auto-generated by Prisma (cuid)
        slug: parsed.data.slug,
        categoryId: parsed.data.categoryId,
        name: parsed.data.name,
        nameEn: parsed.data.nameEn,
        meta: parsed.data.meta,
        description: parsed.data.description,
        price: parsed.data.price,
        originalPrice: parsed.data.originalPrice ?? null,
        badge: parsed.data.badge ?? null,
        badgeType: parsed.data.badgeType ?? null,
        sku: parsed.data.sku,
        stock: parsed.data.stock,
        image: parsed.data.image,
        images,
        specs,
        sizes,
        careInstructions: parsed.data.careInstructions ?? null,
        sortOrder: parsed.data.sortOrder,
        isActive: parsed.data.isActive,
        isFeatured: parsed.data.isFeatured,
      },
    });
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : "שגיאה ביצירה" };
  }
  revalidatePath("/admin/products");
  redirect("/admin/products");
}

export async function updateProduct(
  productId: string,
  _: ProductFormState,
  formData: FormData
): Promise<ProductFormState> {
  await assertAdmin();
  const parsed = productSchema.safeParse(formDataToObject(formData));
  if (!parsed.success) {
    const fe: ProductFormState["fieldErrors"] = {};
    for (const issue of parsed.error.issues) {
      const k = issue.path[0] as keyof z.infer<typeof productSchema>;
      if (!fe[k]) fe[k] = issue.message;
    }
    return { ok: false, error: "ולידציה נכשלה", fieldErrors: fe };
  }
  const { images, specs, sizes } = parseTextLists(parsed.data);
  // Detect 0 → >0 transition so we can fire the restock waitlist
  // notifications afterwards. Fetch the current stock first.
  const previous = await prisma.product.findUnique({
    where: { id: productId },
    select: { stock: true },
  });
  const wasOutOfStock = (previous?.stock ?? 0) === 0;
  const willBeInStock = parsed.data.stock > 0;
  try {
    await prisma.product.update({
      where: { id: productId },
      data: {
        slug: parsed.data.slug,
        categoryId: parsed.data.categoryId,
        name: parsed.data.name,
        nameEn: parsed.data.nameEn,
        meta: parsed.data.meta,
        description: parsed.data.description,
        price: parsed.data.price,
        originalPrice: parsed.data.originalPrice ?? null,
        badge: parsed.data.badge ?? null,
        badgeType: parsed.data.badgeType ?? null,
        sku: parsed.data.sku,
        stock: parsed.data.stock,
        image: parsed.data.image,
        images,
        specs,
        sizes,
        careInstructions: parsed.data.careInstructions ?? null,
        sortOrder: parsed.data.sortOrder,
        isActive: parsed.data.isActive,
        isFeatured: parsed.data.isFeatured,
      },
    });
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : "שגיאה בעדכון" };
  }
  // Restock notification — fire-and-forget. Lazy-imported so this
  // dependency doesn't load when stock didn't transition.
  if (wasOutOfStock && willBeInStock) {
    const { notifyRestockWaitlist } = await import("@/lib/restock-actions");
    notifyRestockWaitlist(productId).catch(() => {});
  }
  revalidatePath("/admin/products");
  revalidatePath(`/product/${parsed.data.slug}`);
  redirect("/admin/products");
}

export async function deleteProduct(productId: string) {
  await assertAdmin();
  try {
    await prisma.product.delete({ where: { id: productId } });
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : "שגיאה במחיקה" };
  }
  revalidatePath("/admin/products");
  return { ok: true };
}

export async function toggleProductActive(productId: string, isActive: boolean) {
  await assertAdmin();
  await prisma.product.update({ where: { id: productId }, data: { isActive } });
  revalidatePath("/admin/products");
}

export async function toggleProductFeatured(productId: string, isFeatured: boolean) {
  await assertAdmin();
  await prisma.product.update({ where: { id: productId }, data: { isFeatured } });
  revalidatePath("/admin/products");
}
